---
- name: Test connection my server
  become: yes
  gather_facts: no
  hosts: tru
  #------------------------------------------------s1
  vars_files:
  - vars1.yml
  - vars.yml
  

  tasks:
     - name: Print varible
       include: s2-update-apt.yml

 
        
    
