---
- name: Test with include files
  become: yes
  gather_facts: no
  hosts: tru
  #------------------------------------------------s1
  vars_files:
  - vars1.yml
  - vars.yml
  

  tasks:
     - name: update apt and ping
       include_tasks: s2-update-apt.yml

     - name: debug vars
       include_tasks: s3-vars-debug.yml
 
        
    
