---
- name: Установка SSL-сертификата с Let’s Encrypt
  become: yes
  hosts: tru

  vars:
    domain: truruki.ru
    email: 89134038088@mail.ru
    acme_account_key: /etc/letsencrypt/account.key
    private_key_path: /etc/letsencrypt/{{ domain }}.key
    csr_path: /etc/letsencrypt/{{ domain }}.csr
    cert_path: /etc/letsencrypt/{{ domain }}.crt
    fullchain_path: /etc/letsencrypt/{{ domain }}-fullchain.crt
    webroot: /var/www/trur/


  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /etc/letsencrypt
        state: directory
        mode: 0600
         
    - name: Генерация приватного ключа для домена
      community.crypto.openssl_privatekey:
        path: "{{ private_key_path }}"
        size: 4096
        type: RSA

    - name: Create account key
      community.crypto.openssl_privatekey:
        path: /etc/letsencrypt/account.key
        size: 4096
        type: RSA

    - name: Генерация CSR для домена
      community.crypto.openssl_csr:
        path: "{{ csr_path }}"
        privatekey_path: "{{ private_key_path }}"
        common_name: "{{ domain }}"
        subject_alt_name:
          - DNS:{{ domain }}

    - name: Получение challenge от Let's Encrypt (фаза 1)
      community.crypto.acme_certificate:
        account_key_src: "{{ acme_account_key }}"
        csr: "{{ csr_path }}"
        dest: "{{ cert_path }}"
        fullchain_dest: "{{ fullchain_path }}"
        challenge: http-01
        acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
        terms_agreed: true
        acme_version: 2
        account_email: "{{ email }}"
        data: {}
      register: acme_challenge
    
    - name: Разместить challenge-файл на веб-сервере      
      copy:
        content: "{{ acme_challenge.challenge_data[domain]['http-01']['resource_value'] }}"
        dest: "{{ webroot }}/{{ acme_challenge.challenge_data[domain]['http-01']['resource'] }}"
        mode: '0644'


    - name: Завершение получения сертификата (фаза 2)
      community.crypto.acme_certificate:
        account_key_src: "{{ acme_account_key }}"
        csr: "{{ csr_path }}"
        dest: "{{ cert_path }}"
        fullchain_dest: "{{ fullchain_path }}"
        challenge: http-01
        acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
        terms_agreed: true
        acme_version: 2
        account_email: "{{ email }}"
        data: "{{ acme_challenge }}"
      when: acme_challenge['challenge_data'] is defined
    
#------------------------------------------------
    - name: Insert/Update configuration using a local file
      ansible.builtin.blockinfile:
        path: /etc/nginx/sites-available/truruki
        block: "{{ lookup('ansible.builtin.file', './files/truruki/new_frag12') }}"
        marker: "## {mark} ANSIBLE MANAGED BLOCK"

    - name: adding a line
      lineinfile:
        path: /etc/nginx/sites-available/truruki
        insertafter: '^listen 80;'
        line: 'return 301 https://truruki.ru$request_uri;'

    - name: Reload nginx
      service:
        name: nginx
        state: reloaded